if(NOT DEFINED LOCK OR NOT EXISTS "${LOCK}")
  message(FATAL_ERROR "LOCK must point to toolchains/wasi-sdk.lock")
endif()
if(NOT DEFINED ARCHIVE OR NOT EXISTS "${ARCHIVE}")
  message(FATAL_ERROR "ARCHIVE must point to the wasi-sdk release archive")
endif()

file(STRINGS "${LOCK}" _lock_lines)
foreach(_line IN LISTS _lock_lines)
  if(_line MATCHES "^version=(.+)$")
    set(_version "${CMAKE_MATCH_1}")
  elseif(_line MATCHES "^asset=(.+)$")
    set(_asset "${CMAKE_MATCH_1}")
  elseif(_line MATCHES "^sha256=([0-9a-fA-F]+)$")
    string(TOLOWER "${CMAKE_MATCH_1}" _expected_sha)
  endif()
endforeach()

if(NOT _version OR NOT _asset OR NOT _expected_sha)
  message(FATAL_ERROR "Malformed wasi-sdk lock file")
endif()

get_filename_component(_archive_name "${ARCHIVE}" NAME)
if(NOT _archive_name STREQUAL _asset)
  message(FATAL_ERROR "Archive name mismatch: expected ${_asset}, got ${_archive_name}")
endif()

file(SHA256 "${ARCHIVE}" _actual_sha)
string(TOLOWER "${_actual_sha}" _actual_sha)
if(NOT _actual_sha STREQUAL _expected_sha)
  message(FATAL_ERROR "wasi-sdk SHA-256 mismatch: expected ${_expected_sha}, got ${_actual_sha}")
endif()

message(STATUS "Verified ${_version}")
